### ISSUE TITLE
Better pattern

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/pathroles#3]
@coolaj86 You had a better pattern for this purpose. Was it something like this?

```js
app.use('/api/*', pathroles({ roles: ['user', 'admin']}));
```

**Comment by coolaj86** [comment]
```js
app.use('/api/*', pathroles({ method: ['GET', 'POST'], roles: ['user', 'admin'] }));
```

**Comment by ryanburnette** [comment]
That’s a more explicit and maintainable pattern. I’m going to rewrite for
this usage.

**Comment by ryanburnette** [comment]
@coolaj86 v2.0.0 is simpler and I definitely like this pattern better. Thanks again.
