### ISSUE TITLE
Where on the req object are the roles?

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/pathroles#5]
@coolaj86 I need to configure the location of the roles array on the req object. Right now it looks to req.users for a roles array as an attribute of that object. I don’t want a breaking change, but I’d like to pass that as a confit opt. Can you PR for that?

**Comment by coolaj86** [comment]
Sure. I can also `req.user = Object.assign({}, req.jws.claims)`;

**Comment by ryanburnette** [comment]
This is fine the way it is, but it needed to be in the readme.
